spring:
  jackson:
    time-zone: GMT+8
    deserialization:
      accept_empty_string_as_null_object: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 1KB
      # 最大文件大小
      max-file-size: 30MB
      # 最大请求大小
      max-request-size: 50MB
  sql:
    init:
      #创建表的MySql语句位置
      schema-locations: classpath:database/schema.sql
      #插入数据的MySql语句的位置
      data-locations: classpath:database/data.sql

  h2:
    console:
    #default true。咱也可以用命令行访问好数据库，感兴趣的同学点这个链接 http://www.h2database.com/html/tutorial.html?highlight=Mac&search=mac#firstFound
    enabled: true
    #console url。Spring启动后，可以访问 http://127.0.0.1:8080/h2-console 查看数据库
    path: /h2-console
    settings:
    trace: true
    #remote visit
    web-allow-others: true
  thymeleaf:
    # THYMELEAF (ThymeleafAutoConfiguration)
    # 开启模板缓存（默认值： true ）
    cache: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    #Content-Type 的值（默认值： text/html ）
    content-type: text/html
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    excluded-view-names: ''
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: HTML
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
mybatis:
  #下面这些内容是为了让MyBatis映射
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.ethereal.kernel.mybatis.entity

logging:
  config: classpath:logback-spring.xml